version: "3.9"

services:
  meshtastic-relay:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meshtastic-relay
    volumes:
      - ./data:/app/data
      - ./data/logs:/logs
      - ./data/config.yaml:/app/config.yaml
    restart: unless-stopped
